### ISSUE TITLE
Inconsistent Ascent between Windows and Macs

### ISSUE THREAD

**Issue by briarsweetbriar** [fontello/svg2ttf#48]
We're getting inconsistent rendering on Windows and Macs. Macs fonts display as expected, while Windows fonts have a large amount of whitespace on top. We've tracked it down to these lines:

For Windows, it gets the greater of the yMax or ascent: https://github.com/fontello/svg2ttf/blob/master/lib/ttf/tables/os2.js#L66

While for Macs, it's just getting the ascent: https://github.com/fontello/svg2ttf/blob/master/lib/ttf/tables/hhea.js#L12

Is this intended? If not, we'd be happy to submit a PR.

**Comment by puzrin** [comment]
At first, i'd like to say that I'm not competent in font rendering deals. This project started just to pack icons somehow at fontello and i did not expected more wide use.

If you are experienced in this area and know what you do - any PR will be welcome.

Lines you refer have comment above https://github.com/fontello/svg2ttf/blob/master/lib/ttf/tables/os2.js#L65. Blame show this commit https://github.com/fontello/svg2ttf/commit/3c8646a50ec48726d87003c178391209f0e89c15.

So, yes, we had a problem with clipping of big glyphs (out of acsent/descent), but i'm not sure that fix is right.

**Comment by null-null-null** [comment]
We're definitely not experts in this either, though we haven't noticed any clipping in our glyphs with our solution. That being said, it might not be a general solution. Out glyphs are only 512 high.

**Comment by puzrin** [comment]
> Out glyphs are only 512 high.

That doesn't cover problem case. Problem happens (if it still exists) if glyph height is > ascent+descent. Absolute height value does not matters.

If you can test all ranges from Win XP and IE8, and bug does not appears, then we can roll back that patch. I can't organize such testing now because switched to main project (nodeca). Need to fihish it at last.

**Comment by null-null-null** [comment]
Do you have a glyph on hand that meets those criteria? I could test out our solution with it.

**Comment by puzrin** [comment]
1. The most simple test case is dark circle, 5% bigger than glyph max/min lines. If problem exists, then round parts at top and bottom become the horisontal lines.
2. http://fontello.com/#search=vector this icon (first) is a real example out borders.

Note: DON'T use ttfautohint for post-processing, because it can fix problem somehow (did not decompiled with ttx to investigate).

**Comment by uchihamalolan** [comment]
If #96 is merged, the one can pass option `useTypoMetrics: true` as one of the options. This will make sure windows uses `typoMetrics` to calculate ascent and descent.
